spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gigmanager
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
firebase:
  service-account-path: firebase-service-account.json

server:
  port: 8080
