name: CI- iOS

on:
  pull_request:
    branches: [development, main]
    paths:
      - "mobile/**"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Select XCode 26
        run: sudo xcode-select -s /Applications/XCode_26.3.app/Contents/Developer

      - name: Build iOS app
        run: |
          xcodebuild build \
            -project mobile/GigManager/GigManager.xcodeproj \
            -scheme GigManager \
            -destination 'generic/platform=iOS Simulator' \
            CODE_SIGNING_ALLOWED=NO
